/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { Fd } from "./Fd";
import { FdCountArgs } from "./FdCountArgs";
import { FdFindManyArgs } from "./FdFindManyArgs";
import { FdFindUniqueArgs } from "./FdFindUniqueArgs";
import { DeleteFdArgs } from "./DeleteFdArgs";
import { FdService } from "../fd.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => Fd)
export class FdResolverBase {
  constructor(
    protected readonly service: FdService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "Fd",
    action: "read",
    possession: "any",
  })
  async _fdsMeta(@graphql.Args() args: FdCountArgs): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [Fd])
  @nestAccessControl.UseRoles({
    resource: "Fd",
    action: "read",
    possession: "any",
  })
  async fds(@graphql.Args() args: FdFindManyArgs): Promise<Fd[]> {
    return this.service.fds(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => Fd, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Fd",
    action: "read",
    possession: "own",
  })
  async fd(@graphql.Args() args: FdFindUniqueArgs): Promise<Fd | null> {
    const result = await this.service.fd(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Fd)
  @nestAccessControl.UseRoles({
    resource: "Fd",
    action: "delete",
    possession: "any",
  })
  async deleteFd(@graphql.Args() args: DeleteFdArgs): Promise<Fd | null> {
    try {
      return await this.service.deleteFd(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
